version: "3"
services:
  app:
    container_name: Sport_App_Jakin
    build: .
    # This command overrides the Dockerfile CMD to ensure watching works
    command: nodemon -L back-end/app.js
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
      
      - /usr/src/app/node_modules
    links:
      - "mongo"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      # This saves your database data in a folder named 'data' so you don't lose it
      - ./data:/data/db
    ports:
      - "27017:27017"